### ISSUE TITLE
Can't release Rolling release

### ISSUE THREAD

**Issue by facontidavide** [ros2-gbp/plotjuggler-ros-plugins-release#1]
Hi,

I get this error:

```
ERROR: Permission to ros2-gbp/plotjuggler-ros-plugins-release.git denied to facontidavide.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Cannot push to remote release repository.
Hint: If you just typed in your username/password and you have two-factor authentication,see:
  http://wiki.ros.org/bloom/Tutorials/GithubManualAuthorization

```

Any suggestion?

**Comment by nuclearsandwich** [comment]
I am still in the process of updating the recently announced https://github.com/ros2-gbp/ros2-gbp-github-org repository with teams from the recent migration of Rolling. I'm hoping to have the first draft of updates out later today and if I don't get the full set I'll be sure to cherry pick out the plotjuggler repositories to unblock your releases.

I'll update this issue when I've done so. Thanks!

**Comment by nuclearsandwich** [comment]
@facontidavide ros2-gbp/ros2-gbp-github-org#6 has merged and deployed which should grant you access to the plotjuggler release repositories. Please let me know if you have any other questions or issues. Thanks!
